name: MCP Core Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'libs/mcp-core/**'
      - '.github/workflows/tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'libs/mcp-core/**'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

jobs:
  test-mcp-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            libs/mcp-core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install mcp-hello-world node dependencies
        run: cd libs/mcp-core/tests/it/resources/mcp-server-hello-world && npm i && cd -

      - name: Run mcp-core tests
        run: npm run test:mcp-core
          
      - name: Run clippy
        working-directory: libs/mcp-core
        run: cargo clippy -- -D warnings
